# Generated by Django 5.2.8 on 2026-01-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membershiphistory_status_membershipfreeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='area',
        ),
    ]
