# Generated by Django 5.2.8 on 2026-01-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_area'),
        ('superadmin', '0010_gym_gst_number_alter_gym_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'email'), ('gym', 'mobile_number')},
        ),
    ]
