# Generated by Django 5.2.8 on 2026-01-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_workoutplan_created_by_workoutplan_image'),
        ('members', '0005_alter_member_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.dietplan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_diet_plans', to='members.member')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to='members.member')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.workoutplan')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
