# Generated by Django 5.2.8 on 2026-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_membershiphistory_cgst_membershiphistory_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
