# Generated by Django 5.2.8 on 2026-01-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_duration_minutes_workoutplan_duration_days'),
        ('members', '0008_alter_member_identity_type'),
        ('superadmin', '0014_gym_password_reset_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignworkoutplan',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='assignworkoutplan',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='assignworkoutplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_members', to='management.workoutplan'),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
