# Generated by Django 5.2.8 on 2026-01-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_duration_minutes_workoutplan_duration_days'),
        ('members', '0009_remove_assignworkoutplan_workout_plan_and_more'),
        ('superadmin', '0014_gym_password_reset_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigndietplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignworkoutplan',
            options={},
        ),
        migrations.RenameField(
            model_name='membershiphistory',
            old_name='is_trashed',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='personaltrainer',
            old_name='is_trashed',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='assignworkoutplan',
            name='plan',
        ),
        migrations.AddField(
            model_name='assigndietplan',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='assignworkoutplan',
            name='workout_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.workoutplan'),
        ),
        migrations.AlterField(
            model_name='assigndietplan',
            name='diet_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.dietplan'),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
