# Generated by Django 5.2.8 on 2026-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_assigndietplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
