# Generated by Django 5.2.8 on 2026-01-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_membershiphistory_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='personaltrainer',
            name='invoice_id',
        ),
    ]
