# Generated by Django 5.2.8 on 2026-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relation',
            field=models.CharField(blank=True, choices=[('Myself', 'Myself'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Other', 'Other')], default='Myself', max_length=50, null=True),
        ),
    ]
