# Generated by Django 5.2.8 on 2026-02-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_relation'),
        ('superadmin', '0016_alter_gym_attendance_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'email'), ('gym', 'mobile_number', 'relation')},
        ),
    ]
