# Generated by Django 5.2.8 on 2026-02-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_member_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='expiry_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
