# Generated by Django 5.2.8 on 2026-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_membershiphistory_expiry_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='reminder_2_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='reminder_4_days_sent',
            field=models.BooleanField(default=False),
        ),
    ]
