# Generated by Django 5.2.8 on 2026-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_membershiphistory_reminder_2_days_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_birthday_wish_sent_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
