# Generated by Django 5.2.8 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_member_last_birthday_wish_sent_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
