# Generated by Django 5.2.8 on 2026-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_membershiphistory_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
