# Generated by Django 5.2.8 on 2026-03-13 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_personaltrainer_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
