# Generated by Django 5.2.8 on 2026-03-13 11:18

from django.db import migrations

def backfill_payment_date(apps, schema_editor):
    MembershipHistory = apps.get_model('members', 'MembershipHistory')
    for history in MembershipHistory.objects.all():
        history.payment_date = history.membership_start_date
        history.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_membershiphistory_payment_date'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_date),
    ]