# Generated by Django 5.2.8 on 2026-03-13 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20260313_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
