# Generated by Django 5.2.8 on 2026-04-11 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_personaltrainer_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
