# Generated by Django 5.2.14 on 2026-10-03 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_member_user'),
        ('superadmin', '0025_saasupgraderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Body weight in kg', max_digits=5)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Body fat %', max_digits=4, null=True)),
                ('chest_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Chest (inches)', max_digits=4, null=True)),
                ('waist_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Waist (inches)', max_digits=4, null=True)),
                ('biceps_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Arms / Biceps (inches)', max_digits=4, null=True)),
                ('thighs_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Thighs (inches)', max_digits=4, null=True)),
                ('notes', models.CharField(blank=True, help_text='Progress notes or weekly observations', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_body_metrics', to='superadmin.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(help_text='e.g. Chest & Triceps Blast, Leg Day, Back & Biceps', max_length=150)),
                ('workout_type', models.CharField(choices=[('strength', 'Strength & Resistance'), ('cardio', 'Cardio & Conditioning'), ('hiit', 'HIIT & Circuit'), ('crossfit', 'CrossFit & Functional'), ('yoga', 'Yoga & Mobility'), ('recovery', 'Active Recovery & Stretching')], default='strength', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=45, help_text='Total workout duration in minutes')),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned', null=True)),
                ('energy_rating', models.PositiveSmallIntegerField(default=4, help_text='Rating 1-5')),
                ('notes', models.TextField(blank=True, help_text='Workout reflections, PRs, or trainer feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_workout_logs', to='superadmin.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='e.g. Barbell Bench Press, Barbell Squat', max_length=150)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10-12', help_text='e.g. 12, 10, 8 or 10-12', max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight lifted in kg', max_digits=6)),
                ('notes', models.CharField(blank=True, help_text='e.g. Drop set on last, felt strong', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='members.memberworkoutlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
