# Generated by Django 5.2.14 on 2026-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_memberbodymetric_memberworkoutlog_memberexerciselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbodymetric',
            name='biceps_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Arms / Biceps (inches)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberbodymetric',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body fat %', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberbodymetric',
            name='chest_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chest (inches)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberbodymetric',
            name='thighs_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thighs (inches)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberbodymetric',
            name='waist_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Waist (inches)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberbodymetric',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Body weight in kg', max_digits=7),
        ),
        migrations.AlterField(
            model_name='memberexerciselog',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight lifted in kg', max_digits=7),
        ),
    ]
