# Generated by Django 5.2.14 on 2026-10-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_alter_memberbodymetric_biceps_inches_and_more'),
        ('superadmin', '0025_saasupgraderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss & Fat Reduction'), ('muscle_gain', 'Muscle Building & Bulking'), ('body_recomp', 'Body Recomposition & Toning'), ('endurance', 'Cardio & Stamina Building'), ('strength', 'Strength & Powerlifting')], default='weight_loss', max_length=50)),
                ('starting_weight_kg', models.DecimalField(decimal_places=2, help_text='Starting baseline weight in kg', max_digits=7)),
                ('target_weight_kg', models.DecimalField(decimal_places=2, help_text='Target goal weight in kg', max_digits=7)),
                ('target_body_fat', models.DecimalField(blank=True, decimal_places=2, help_text='Target body fat %', max_digits=6, null=True)),
                ('target_weekly_workouts', models.PositiveSmallIntegerField(default=4, help_text='Target workouts per week')),
                ('target_date', models.DateField(blank=True, help_text='Target deadline date to reach the goal', null=True)),
                ('motivation_notes', models.CharField(blank=True, help_text='Personal mantra, motivation or reason for goal', max_length=255)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_fitness_goals', to='superadmin.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
