# Generated by Django 5.2.14 on 2026-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_memberfitnessgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbodymetric',
            name='photo',
            field=models.ImageField(blank=True, help_text='Physique / Transformation progress photo', null=True, upload_to='progress_photos/'),
        ),
    ]
