"""
Django settings for GYM project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-q_2uz@czn8zn!aks2)zxc3v4z28h4=3&ge1e6ex5afr&^e#-t3')
# In production, set environment variable DJANGO_DEBUG=False
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'fitstack.nextgenapplication.com,127.0.0.1,localhost').split(',') if h.strip()]
for default_host in ['localhost', '127.0.0.1', 'testserver']:
    if default_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(default_host)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://fitstack.nextgenapplication.com,https://fitness.nextgenapplication.com').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'ckeditor',
    'apps.dashboard',
    'apps.members',
    'apps.enquiry',
    'apps.trainers',
    'apps.management',
    'apps.billing',
    'apps.attendance',
    'apps.expenses',
    'apps.settings',
    'apps.superadmin',
    'apps.business_report',
    'apps.events',
    'apps.inventory',
    'apps.login',
    'apps.whatsapp',
    'apps.website',
    'apps.member_portal',
    'apps.trainer_portal',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'GYM.tenant_middleware.TenantMiddleware',
    'apps.login.middleware.PasswordResetMiddleware',
]

ROOT_URLCONF = 'GYM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.superadmin.context_processors.gym_details',
                'apps.settings.context_processors.payment_settings_context',
                'apps.login.context_processors.registration_credentials_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GYM.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 600,  # Reuse DB connections for 10 minutes
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'gymdb'),
#         'USER': os.environ.get('DB_USER', 'postgres'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', ''),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),    
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True



# ============ WhatsApp Configuration (Legacy/Cloud API) ============
# WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
# WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
# WHATSAPP_VERIFY_TOKEN = os.environ.get('WHATSAPP_VERIFY_TOKEN', '')
# WHATSAPP_REGISTRATION_PIN = os.environ.get('WHATSAPP_REGISTRATION_PIN', '')
# WHATSAPP_API_VERSION = 'v22.0' 
# WHATSAPP_WEBHOOK_URL = '/whatsapp/webhook/'
# WHATSAPP_BASE_URL = f'https://graph.facebook.com/{WHATSAPP_API_VERSION}'
# WHATSAPP_CLOUD_API_URL = f'{WHATSAPP_BASE_URL}/{WHATSAPP_PHONE_NUMBER_ID}'
# WHATSAPP_APP_SECRET = os.environ.get('WHATSAPP_APP_SECRET', '')
# WHATSAPP_VERIFICATION_CERTIFICATE = os.environ.get('WHATSAPP_VERIFICATION_CERTIFICATE', '')


#============ WhatsApp Configuration (Twilio) ============
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_NUMBER = os.environ.get('TWILIO_WHATSAPP_NUMBER', '')
TWILIO_CONTENT_SID = os.environ.get('TWILIO_CONTENT_SID', '') # Enquiry confirmation
TWILIO_MEMBERSHIP_ASSIGN_SID = os.environ.get('TWILIO_MEMBERSHIP_ASSIGN_SID', '') # Membership assignment
TWILIO_MEMBERSHIP_EXPIRED_SID = os.environ.get('TWILIO_MEMBERSHIP_EXPIRED_SID', '') # Membership expired
TWILIO_MEMBERSHIP_EXPIRING_SOON_SID = os.environ.get('TWILIO_MEMBERSHIP_EXPIRING_SOON_SID', '') # Membership expiring soon
TWILIO_BIRTHDAY_WISHES_SID = os.environ.get('TWILIO_BIRTHDAY_WISHES_SID', '') # Birthday wishes
TWILIO_DUE_PAYMENT_SID = os.environ.get('TWILIO_DUE_PAYMENT_SID', '') # Due payment received
TWILIO_DUE_FOLLOW_UP_SID = os.environ.get('TWILIO_DUE_FOLLOW_UP_SID', '') # Due follow-up date reminder

# Static files     
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ITEMS_PER_PAGE = 15
LOGOUT_REDIRECT_URL = '/'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 7200  # 2 hours in seconds

# ============ FIXED LOGGING CONFIGURATION ============
# First, create logs directory if it doesn't exist
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'whatsapp.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'apps.whatsapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
# ============ End Logging Configuration ============