# Generated by Django 6.0.1 on 2026-01-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_payment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
