# Generated by Django 5.0.1 on 2024-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_payment_invoice_delete_invoice'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
    ]