# Generated by Django 5.0.1 on 2024-02-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20240226_1415'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.membershiphistory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='personal_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.personaltrainer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]