# Generated by Django 5.0.1 on 2024-02-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20240226_1415'),
        ('members', '0001_initial'),
    ]

    operations = [
    ]