# Generated by Django 5.0.1 on 2024-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20240226_1423'),
    ]

    operations = [
    ]