# Generated by Django 5.2.8 on 2026-02-16 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0016_alter_gym_attendance_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('api_version', models.CharField(default='v19.0', max_length=10)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='superadmin.gym')),
            ],
        ),
    ]
