# Generated by Django 5.2.14 on 2026-09-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_subscriptionplan_color_theme_and_more'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(help_text='Name of recipient (member, lead, admin)', max_length=150)),
                ('recipient_phone', models.CharField(help_text='Phone number', max_length=30)),
                ('recipient_type', models.CharField(blank=True, default='Lead/Contact', max_length=50)),
                ('message_type', models.CharField(choices=[('enquiry', 'Enquiry Follow-up'), ('broadcast', 'Broadcast Announcement'), ('lead', 'Website Lead Contact'), ('renewal', 'Subscription / Fee Renewal'), ('welcome', 'Welcome Onboarding'), ('reminder', 'General Reminder'), ('direct_chat', 'Direct Personal Chat'), ('custom', 'Custom Message')], default='custom', max_length=30)),
                ('message_content', models.TextField(help_text='Message text sent or attempted')),
                ('status', models.CharField(choices=[('sent', 'Sent / Delivered'), ('failed', 'Failed / Not Sent'), ('pending', 'Pending'), ('sent_manually', 'Sent with Personal WhatsApp')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Failure reason if delivery failed', null=True)),
                ('provider', models.CharField(default='twilio', help_text='e.g. twilio, personal_whatsapp', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='superadmin.gym')),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
