# Generated by Django 5.2.14 on 2026-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Sent / Outgoing'), ('inbound', 'Received / Incoming')], default='outbound', max_length=15),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_content',
            field=models.TextField(help_text='Message text sent or received'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_type',
            field=models.CharField(choices=[('enquiry', 'Enquiry Follow-up'), ('broadcast', 'Broadcast Announcement'), ('lead', 'Website Lead Contact'), ('renewal', 'Subscription / Fee Renewal'), ('welcome', 'Welcome Onboarding'), ('reminder', 'General Reminder'), ('direct_chat', 'Direct Personal Chat'), ('inbound_reply', 'Incoming Customer Message'), ('custom', 'Custom Message')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='recipient_name',
            field=models.CharField(help_text='Name of recipient or sender', max_length=150),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent / Delivered'), ('received', 'Received / Inbound'), ('failed', 'Failed / Not Sent'), ('pending', 'Pending'), ('sent_manually', 'Sent with Personal WhatsApp')], default='pending', max_length=20),
        ),
    ]
