# Generated by Django 5.2.8 on 2026-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_description_maintenance_issue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements & Nutrition'), ('beverages', 'Beverages'), ('equipment', 'Gym Equipment (Assets)'), ('accessories', 'Gym Accessories'), ('cleaning', 'Cleaning & Hygiene'), ('medical', 'Medical & First Aid'), ('merchandise', 'Merchandise'), ('office', 'Office & Stationery'), ('maintenance', 'Maintenance & Repair'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='reason',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('internal_use', 'Internal Use'), ('damage', 'Damage'), ('expired', 'Expired'), ('return', 'Return')], default='sale', max_length=20, null=True),
        ),
    ]
