# Generated by Django 5.2.8 on 2026-01-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklog_phone_number_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('free_weights', 'Free Weights'), ('benches_racks', 'Benches & Racks'), ('functional', 'Functional Training'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
