# Generated by Django 5.2.8 on 2026-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_equipment_gym_item_gym_maintenance_gym_stocklog_gym_and_more'),
        ('superadmin', '0010_gym_gst_number_alter_gym_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('gym', 'name'), ('gym', 'sku')},
        ),
    ]
