# Generated by Django 5.2.8 on 2026-01-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_name_alter_item_sku_and_more'),
        ('superadmin', '0010_gym_gst_number_alter_gym_gst_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('gym', 'name')},
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
