# Generated by Django 5.2.8 on 2026-01-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocklog_discount_stocklog_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklog',
            name='tax',
        ),
    ]
