# Generated by Django 5.2.8 on 2025-12-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=100)),
                ('gym_logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('timezone', models.CharField(default='IST', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('invoice_prefix', models.CharField(default='GYM-INV-', max_length=20)),
                ('member_id_format', models.CharField(default='GYM-MEM-', max_length=20)),
            ],
        ),
    ]
