# Generated by Django 5.2.8 on 2025-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bhatt Gym', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logo/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('member_id_format', models.CharField(default='MEM-', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
    ]
