# Generated by Django 5.2.8 on 2025-12-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_generalsetting_delete_generalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSetting',
        ),
    ]
