# Generated by Django 5.2.8 on 2026-01-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0003_delete_generalsetting'),
        ('superadmin', '0011_rename_pincode_gym_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_method', models.CharField(choices=[('qr_code', 'QR Code'), ('biometrics', 'Biometrics'), ('manual', 'Manual')], default='qr_code', max_length=20)),
                ('access_restrictions', models.TextField(blank=True, help_text='Define access restrictions, e.g., time-based access, certain areas only.')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
            ],
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate in percentage.', max_digits=5)),
                ('invoice_template', models.TextField(blank=True, help_text='HTML template for invoices.')),
                ('payment_gateway', models.CharField(blank=True, help_text='e.g., Stripe, PayPal', max_length=50)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_reminder_days', models.PositiveIntegerField(default=7, help_text='Days before membership expiry to send renewal reminders.')),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Grace period in days after membership expires.')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_member_email', models.TextField(blank=True, help_text='Email template for new member registration.')),
                ('payment_reminder_sms', models.TextField(blank=True, help_text='SMS template for payment reminders.')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
            ],
        ),
    ]
