# Generated by Django 5.2.8 on 2026-01-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='billingsettings',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='membershipsettings',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='gym',
        ),
        migrations.DeleteModel(
            name='AccessControlSettings',
        ),
        migrations.DeleteModel(
            name='BillingSettings',
        ),
        migrations.DeleteModel(
            name='MembershipSettings',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
