# Generated by Django 5.2.8 on 2026-01-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_paymentsetting_account_holder_name_and_more'),
        ('superadmin', '0012_rename_official_email_gym_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetting',
            name='gym',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
    ]
