# Generated by Django 5.2.8 on 2026-01-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=255)),
                ('sub_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='login.subadmin')),
            ],
        ),
    ]
