# Generated by Django 5.2.8 on 2026-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_subadminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'Sub Admin'), ('front_desk', 'Front Desk'), ('trainer', 'Trainer'), ('manager', 'Manager'), ('accounts', 'Accounts'), ('inventory', 'Inventory Manager'), ('marketing', 'Marketing / CRM')], default='subadmin', max_length=20),
        ),
    ]
