# Generated by Django 5.2.8 on 2025-12-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_gymsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gym',
        ),
    ]
