# Generated by Django 5.2.8 on 2025-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_subscriptionplan_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsubscription',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('other', 'Other')], default='cash', max_length=50),
        ),
    ]
