# Generated by Django 5.2.8 on 2025-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_gymsubscription_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymsubscription',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='gymsubscription',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='gymsubscription',
            name='status',
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
