# Generated by Django 5.2.8 on 2025-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_remove_gymsubscription_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
