# Generated by Django 5.2.8 on 2025-12-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_gym_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='is_active',
        ),
    ]
