# Generated by Django 5.2.8 on 2025-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_gym_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gst_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
