# Generated by Django 5.2.8 on 2025-12-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_gym_gst_enabled_gym_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gst_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
