# Generated by Django 5.2.8 on 2026-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_gym_gst_number_alter_gym_gst_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='pincode',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='email',
            new_name='official_email',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='landline',
            new_name='primary_contact_number',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='phone',
            new_name='secondary_contact_number',
        ),
        migrations.AddField(
            model_name='gym',
            name='business_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='gym_favicons/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
