# Generated by Django 5.2.8 on 2026-01-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_rename_pincode_gym_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='official_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='primary_contact_number',
            new_name='landline',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='secondary_contact_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='branch',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='support_email',
        ),
    ]
