# Generated by Django 5.2.8 on 2026-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_rename_official_email_gym_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
