# Generated by Django 5.2.8 on 2026-01-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_gym_is_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
