# Generated by Django 5.2.8 on 2026-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_gym_attendance_code_gym_attendance_code_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
