# Generated by Django 5.2.8 on 2026-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_alter_gym_attendance_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='attendance_code_required',
            field=models.BooleanField(default=True),
        ),
    ]
