# Generated by Django 5.2.8 on 2026-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_gym_attendance_code_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsubscription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
