# Generated by Django 5.2.8 on 2026-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_gymsubscription_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable WhatsApp messaging for this gym'),
        ),
    ]
