# Generated by Django 5.2.14 on 2026-09-18 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_gym_whatsapp_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Notification message body')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Notice / Warning'), ('success', 'Update / Success'), ('danger', 'Urgent / Critical Alert')], default='info', max_length=20)),
                ('target_type', models.CharField(choices=[('all', 'All Users (Gyms, Staff & Members)'), ('all_gyms', 'All Gym Admins & Staff Only'), ('all_members', 'All Gym Members Across All Gyms'), ('specific_gym', 'Specific Gym (Admins, Staff & Members)'), ('specific_gym_staff', 'Specific Gym Admins & Staff Only'), ('specific_gym_members', 'Specific Gym Members Only'), ('specific_user', 'Specific User / Member')], default='all', max_length=30)),
                ('show_popup', models.BooleanField(default=False, help_text='Display as an instant interactive popup modal to recipients')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Can the user dismiss without action?')),
                ('action_label', models.CharField(blank=True, help_text="e.g. 'View Details', 'Renew Now'", max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL or path for button', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional auto-expiry datetime', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notifications', to='superadmin.gym')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('popup_acknowledged', models.BooleanField(default=False)),
                ('popup_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='superadmin.platformnotification')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='superadmin__user_id_7cc064_idx'), models.Index(fields=['user', 'popup_acknowledged'], name='superadmin__user_id_faa7b4_idx')],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
