# Generated by Django 5.2.14 on 2026-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_platformnotification_notificationuserstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuserstatus',
            name='popup_last_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationuserstatus',
            name='popup_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformnotification',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner/graphic image', null=True, upload_to='notification_images/'),
        ),
        migrations.AddField(
            model_name='platformnotification',
            name='max_popup_views',
            field=models.PositiveIntegerField(default=1, help_text='Maximum times a user will see this popup (if fixed count is selected)'),
        ),
        migrations.AddField(
            model_name='platformnotification',
            name='popup_frequency',
            field=models.CharField(choices=[('once', 'Once (until dismissed)'), ('every_login', 'Every Login (until expired)'), ('fixed_count', 'Fixed Number of Times (custom view limit)'), ('until_expired', 'Always on every visit until Expired')], default='once', help_text='Frequency of showing popup to users', max_length=30),
        ),
    ]
