# Generated by Django 5.2.8 on 2026-09-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_notificationuserstatus_popup_last_shown_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnotification',
            name='popup_frequency',
            field=models.CharField(choices=[('once', 'Once Only (Dismissed after first view)'), ('every_login', 'On Every Login (Once per session until expired)'), ('fixed_count', 'Impression Cap (Show up to set number of times)'), ('until_expired', 'Persistent (Show on every page visit until expired)')], default='once', help_text='Frequency of showing popup to users', max_length=30),
        ),
    ]
