# Generated by Django 5.2.14 on 2026-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_alter_platformnotification_popup_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='color_theme',
            field=models.CharField(choices=[('blue', 'Sapphire Blue'), ('emerald', 'Emerald Green'), ('purple', 'Royal Purple'), ('amber', 'Sunset Gold'), ('dark', 'Titanium Dark')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_billing_invoicing',
            field=models.BooleanField(default=True, help_text='Invoicing & Dues Tracker'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_biometric_attendance',
            field=models.BooleanField(default=True, help_text='QR / Biometric Attendance System'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_crm_leads',
            field=models.BooleanField(default=True, help_text='Lead CRM & Enquiry Tracking'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_diet_workout',
            field=models.BooleanField(default=True, help_text='Diet & Workout Plan Generation'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_expense_management',
            field=models.BooleanField(default=True, help_text='Expense & Finance Management'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_inventory_management',
            field=models.BooleanField(default=True, help_text='Equipment & Inventory Tracking'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_reports_analytics',
            field=models.BooleanField(default=True, help_text='Business Reports & Analytics'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_staff_salary',
            field=models.BooleanField(default=True, help_text='Trainer Salary & Payroll Tracking'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_whatsapp_support',
            field=models.BooleanField(default=True, help_text='WhatsApp Automated Notifications & Reminders'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for gym assignment'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Highlight as 'Most Popular' / Featured"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_admins',
            field=models.PositiveIntegerField(default=2, help_text='Maximum admin accounts allowed (0 = Unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_members',
            field=models.PositiveIntegerField(default=100, help_text='Maximum members allowed (0 = Unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_trainers',
            field=models.PositiveIntegerField(default=5, help_text='Maximum trainers allowed (0 = Unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='growth', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short subtitle or value proposition', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(help_text='Key perks & marketing highlights (one per line)'),
        ),
    ]
