# Generated by Django 5.2.14 on 2026-10-01 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_subscriptionplan_color_theme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='FitStack', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Next-Gen Gym & Fitness Management SaaS', max_length=255)),
                ('company_name', models.CharField(blank=True, default='FitStack Technologies Inc.', max_length=200)),
                ('support_email', models.EmailField(blank=True, default='support@fitstack.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='+91 88875 58415', max_length=30)),
                ('website_url', models.URLField(blank=True, default='https://fitstack.nextgenapplication.com')),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform_settings/')),
                ('platform_favicon', models.ImageField(blank=True, null=True, upload_to='platform_settings/')),
                ('default_trial_days', models.PositiveIntegerField(default=14, help_text='Default trial duration for new gyms in days')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Grace period days after plan expiry before freeze')),
                ('default_member_prefix', models.CharField(default='MEM', help_text='Default member ID prefix', max_length=10)),
                ('allow_public_registration', models.BooleanField(default=True, help_text='Allow new gyms to self-register from public portal')),
                ('global_whatsapp_master', models.BooleanField(default=True, help_text='Master kill-switch for automated WhatsApp notifications')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable system-wide maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default="FitStack is currently undergoing scheduled maintenance. We'll be back shortly!")),
                ('smtp_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_retention_days', models.PositiveIntegerField(default=30)),
                ('include_media_in_auto_backup', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=120)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('backup_type', models.CharField(choices=[('full', 'Full System Backup'), ('gym', 'Selected Gym Backup'), ('media', 'Media Assets Only')], default='full', max_length=20)),
                ('gym_name', models.CharField(blank=True, max_length=200, null=True)),
                ('includes_database', models.BooleanField(default=True)),
                ('includes_media', models.BooleanField(default=False)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_size_display', models.CharField(default='0 KB', max_length=50)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('manifest_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='superadmin.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
