# Generated by Django 5.2.8 on 2026-01-14 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
