# Generated by Django 5.2.8 on 2026-01-14 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_dietplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
