# Generated by Django 5.2.8 on 2026-01-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_dietplan_created_by_dietplan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='image',
        ),
    ]
