# Generated by Django 5.2.8 on 2026-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_dietplan_created_by_remove_dietplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diet_plans/'),
        ),
    ]
