# Generated by Django 5.2.8 on 2026-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_dietplan_created_by_dietplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_plans/'),
        ),
    ]
