# Generated by Django 5.2.8 on 2026-01-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_workoutplan_created_by_workoutplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('9_months', '9 Months'), ('1_year', '1 Year')], default='1_month', max_length=20),
        ),
    ]
