# Generated by Django 5.2.8 on 2026-01-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_membershipplan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='daily_calories',
            new_name='duration_days',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='duration_weeks',
        ),
    ]
