# Generated by Django 5.2.8 on 2026-01-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_daily_calories_dietplan_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='duration_minutes',
            new_name='duration_days',
        ),
    ]
