# Generated by Django 5.2.8 on 2026-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_duration_minutes_workoutplan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='document',
            field=models.FileField(blank=True, help_text='Upload Image or PDF for Diet Plan Description', null=True, upload_to='diet_plans/docs/'),
        ),
    ]
