# Generated by Django 5.2.8 on 2026-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_dietplan_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='document',
            field=models.FileField(blank=True, help_text='Upload Image or PDF for Workout Plan Description', null=True, upload_to='workout_plans/docs/'),
        ),
    ]
