# Generated by Django 5.2.8 on 2026-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='personal_training_monthly_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('CROSSFIT', 'CrossFit'), ('PT', 'Personal Trainer'), ('ST', 'Strength Training'), ('WL', 'Weight Loss'), ('MB', 'Muscle Building'), ('FT', 'Functional Training'), ('HIIT', 'HIIT'), ('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('CARDIO', 'Cardio Training'), ('REHAB', 'Rehabilitation'), ('NUTRITION', 'Nutrition Coach'), ('SENIOR', 'Senior Fitness Trainer'), ('OTHER', 'Other')], default='CROSSFIT', max_length=100),
        ),
    ]
