# Generated by Django 5.2.8 on 2026-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_rename_pincode_gym_branch_and_more'),
        ('trainers', '0002_alter_trainer_personal_training_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('gym', 'email'), ('gym', 'phone')},
        ),
    ]
