# Generated by Django 5.2.8 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_email_alter_trainer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
