# Generated by Django 5.2.8 on 2026-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='personal_training_monthly_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('CROSSFIT', 'CrossFit Trainer'), ('PT', 'Personal Trainer'), ('ST', 'Strength Training Coach'), ('WL', 'Weight Loss Specialist'), ('MB', 'Muscle Building Coach'), ('FT', 'Functional Training Coach'), ('HIIT', 'HIIT Trainer'), ('YOGA', 'Yoga Instructor'), ('ZUMBA', 'Zumba Instructor'), ('CARDIO', 'Cardio Trainer'), ('CALISTHENICS', 'Calisthenics Coach'), ('MARTIAL', 'Martial Arts Trainer'), ('BOXING', 'Boxing Coach'), ('PILATES', 'Pilates Instructor'), ('REHAB', 'Rehabilitation Specialist'), ('PHYSIO', 'Physiotherapist'), ('NUTRITION', 'Nutrition Coach / Dietitian'), ('SPORTS_DOC', 'Sports Doctor'), ('THERAPIST', 'Sports Therapist'), ('GYM_MANAGER', 'Gym Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('ADMIN', 'Administrator'), ('HR', 'HR Manager'), ('ACCOUNTS', 'Accounts Manager'), ('SALES', 'Sales Executive'), ('COUNSELLOR', 'Fitness Counsellor'), ('FRONT_DESK', 'Front Desk Executive'), ('RECEPTIONIST', 'Receptionist'), ('MAINTENANCE', 'Maintenance Staff'), ('HOUSEKEEPING', 'Housekeeping Staff'), ('SECURITY', 'Security Guard'), ('OTHER', 'Other')], default='CROSSFIT', max_length=100),
        ),
    ]
