# Generated by Django 5.2.8 on 2026-09-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_alter_platformnotification_popup_frequency'),
        ('trainers', '0006_trainer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_days', models.PositiveSmallIntegerField(default=30)),
                ('present_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('half_days', models.PositiveSmallIntegerField(default=0)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('payable_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('base_salary_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pt_clients_count', models.PositiveIntegerField(default=0)),
                ('pt_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft / Review'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer (NEFT/IMPS)'), ('upi', 'UPI / GPay / PhonePe'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_salaries', to='superadmin.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-year', '-month', 'trainer__name'],
                'unique_together': {('trainer', 'month', 'year')},
            },
        ),
    ]
