# Generated by Django 5.2.8 on 2025-12-15 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('superadmin', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=10)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=10)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.trainer')),
            ],
        ),
    ]
