# Generated by Django 5.2.8 on 2026-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('inquiry_type', models.CharField(choices=[('demo', 'Schedule a Demo'), ('pricing', 'Pricing Inquiry'), ('support', 'Technical Support'), ('partnership', 'Partnership Opportunity'), ('other', 'Other Inquiry')], max_length=20)),
                ('referral_source', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
