# Generated by Django 5.2.8 on 2025-12-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='walk_in', max_length=20)),
                ('interested_in', models.CharField(choices=[('gym', 'Gym'), ('zumba', 'Zumba'), ('personal_training', 'Personal Training'), ('yoga', 'Yoga'), ('crossfit', 'CrossFit')], default='gym', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('enquiry_note', models.TextField()),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym')),
            ],
        ),
    ]
