# Generated by Django 5.2.8 on 2025-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
