# Generated by Django 5.2.8 on 2025-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_alter_enquiry_enquiry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
    ]
