# Generated by Django 5.2.8 on 2026-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_alter_enquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='follow_up', max_length=20),
        ),
    ]
