# Generated by Django 5.2.8 on 2026-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_remove_enquiry_date_of_birth_enquiry_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
